logging:
  config: classpath:logback-boot.xml

server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(H+m49N8OZKsO/vsOQv9WfHHXSablzAnsOFyiayEEVTACy6MMoKJnWpvOYn6RzAH3tkulkpboGUZ/G8Zmw/j6mbuxi6DXO1quimwHkcMbUj1cArc/AlWY+5R/3KZIP3CJkT7SKH03nfg=)
    username: ENC(lMDBcJMMAqRDsT68H20IRQ==)
    password: ENC(/qne/C3XsOIv//Ig2NmIFg==)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES

management:
  endpoint:
    shutdown:
      enabled: true